# Generated by Django 4.2.4 on 2023-10-16 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_taken',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
