# Generated by Django 4.2.4 on 2023-10-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library1', '0004_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_to_retur',
            new_name='date_to_return',
        ),
    ]
